### PR TITLE
Add yarn.lock and .yarnclean

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
For those of us who use yarn, these files are nice to have around.  They speed up installs and ensure everyone using yarn is using exactly the same package versions.  NPM users can just ignore them so it works out great for everyone.

### CODE REVIEW

**Comment by developit** [comment]
@AlexanderOtavka any info on how this changes the installation process?  It seems like adding a lockfile would freeze all child dependencies to a hard version, if it's observed by Yarn during install.  That's quite a firm stance on versioning for a little JavaScript library haha.

Also - I think this means we'd have to require that anyone contributing to this repo then use Yarn?  Otherwise the lockfile will get out of sync with the `package.json`, right?

**Comment by AlexanderOtavka** [comment]
The exact behavior is outlined on [yarn's website](https://yarnpkg.com/en/docs/yarn-lock).  Basically, it ensures that unless you explicitly upgrade, everyone stays on the same version.  It's okay if the lockfile gets momentarily out of sync with the `package.json` since using the yarn CLI will bring it back into sync - `package.json` is king.

**Comment by developit** [comment]
@AlexanderOtavka right. It would seem this means I have to use Yarn to manage this package now.

**Comment by AlexanderOtavka** [comment]
Oh, ok.  You should probably add yarn.lock to the .gitignore so yarn users don't accidentally commit it then.  I'll make a PR for that.

**Comment by developit** [comment]
Makes sense - thanks for switching the PRs!  I'm not against using Yarn, just not quite ready to change workflows.

**Pull request closed without merging**
