### PR TITLE
fix onchange trigger twice for select box

### LINKED ISSUE #160: Onchange event on Select box triggers twice
The `onchange` event on my select box triggers twice.
By debugging it, I could find that in this [line](https://github.com/developit/preact-compat/blob/master/src/index.js#L269), there are 2 values being passed to `multihook` function and both the values are same i.e. `onchange`

@developit Can you please help?
If the above is the case and it's a bug, I'll be more than happy to contribute :smile:

### PR DESCRIPTION
**Pull request by chiragmongia**
Fixes #160

### CODE REVIEW

**Comment by developit** [comment]
@chiragmongia wow, that's all that was needed?

**Comment by chiragmongia** [comment]
@developit Yeah, I think that should do it.

**Comment by chiragmongia** [comment]
@developit Anything pending in this?

**Comment by developit** [comment]
Nope, happy to merge. Sorry for the delay!

**Comment by chiragmongia** [comment]
@developit Thanks! :smiley:

**Pull request merged**
