### PR TITLE
Feature/145

### LINKED ISSUE #145: render behaves differently from ReactDOM
https://facebook.github.io/react/docs/top-level-api.html#reactdom.render

> ReactDOM.render() controls the contents of the container node you pass in. Any existing DOM elements inside are replaced when first called. Later calls use React’s DOM diffing algorithm for efficient updates.

That's not what happens with preact-compat

```html
<div id="root">
   Hello
</div>
```

```js
import ReactDOM from 'preact-compat';

ReactDOM.render(<span>Hello</span>, document.getElementById('root'));
```

results in
```html
<div id="root">
   Hello<span>Hello</span>
</div>
```

### PR DESCRIPTION
**Pull request by MobiusHorizons**
Fixes #145

### CODE REVIEW

**Comment by developit** [comment]
I think this makes sense!

**Comment by developit** [comment]
Only thing we'll need is to have it also remove extra elements that may have been contained in `parent` on initial render.  Right now it leaves the `<p>` in the example below:

```html
<div id="app">
  <section id="root">to be rendered by preact-compat</section>
  <p>should be removed since it's not in the vtree</p>
</div>
```

```js
render(<section id="root">rendered</section>, $('#app'));
console.log( $('#app').children.length );  // 2, should be 1
```

**Comment by MobiusHorizons** [comment]
@developit, I have added a test that I believe covers this case. Please see the updated code.

**Comment by developit** [comment]
Might be an issue with multiple node removal here.  `.children` is a Live NodeList and so calling `removeChild()` on the second child actually shifts the list :o

I don't mind tweaking it after merge if you're getting the desired result though, I really appreciate your work on this!

**Comment by MobiusHorizons** [comment]
Good point, I will fix it. I also realized that textnodes in the `parent` wouldn't be taken care of, since they don't show up as children.

**Comment by developit** [comment]
Indeed! Switching to `childNodes` should fix that.

**Comment by MobiusHorizons** [comment]
Alright, I think this covers my use cases. tweak as necessary.

**Comment by developit** [comment]
Looks great, I'll merge as soon as I have a sec!

**Comment by MobiusHorizons** [comment]
cool, glad to hear it.

**Comment by chiragmongia** [comment]
I would love to see this getting merged! :smiley:

**Comment by developit** [comment]
Released as [3.0.0](https://github.com/developit/preact-compat/releases/tag/3.0.0)! 🎉

**Pull request merged**
