### PR TITLE
fix multi cloned element lose props.children bug

### LINKED ISSUE #414: Lose props.children after cloneElement
Preact will not work proper with many library like [react-tabs](https://github.com/reactjs/react-tabs) cause they use cloneElement in there code, and then in preact clonedElement lose props.children props.

I found this is due to the `h` method will remove attributes.children when attributes.children exists.

```
	if (attributes && attributes.children!=null) {
		if (!stack.length) stack.push(attributes.children);
		delete attributes.children;
	}
``` 

I'll try to add a PR to fix this problem.

### PR DESCRIPTION
**Pull request by xxxiin**
fix #414

### CODE REVIEW

**Comment by developit** [comment]
Good find!

**Comment by ethanroday** [comment]
Is this slated for release soon? I'm running into this issue as well and would love to have the fix.

**Comment by ethanroday** [comment]
@developit know you are slammed but any chance of a release soon?

**Comment by developit** [comment]
I can do a release yup

**Comment by developit** [comment]
Done! [3.18.0](https://github.com/developit/preact-compat/releases/tag/3.18.0).

**Comment by ethanroday** [comment]
Awesome! Thank you!

**Pull request merged**
