### PR TITLE
Some libraries parse the version as semver.

### PR DESCRIPTION
**Pull request by ruiaraujo**
Use the current React semver.

I did this to work with react bootstrap.

### CODE REVIEW

**Comment by developit** [comment]
Good catch, I should have considered that! Ignore the build errors, those are on me.

**Comment by ruiaraujo** [comment]
Another release would be great. ;) I dislike pointing npm to git revs.

**Comment by developit** [comment]
Agreed for sure, sorry about that!

**Comment by developit** [comment]
Released as `preact-compat@1.8.3`!

**Comment by ruiaraujo** [comment]
Thanks!

**Pull request merged**
