### PR TITLE
Add internal properties for enzyme test.

### PR DESCRIPTION
**Pull request by windyGex**
I write a package called [`preact-test-utils`](https://github.com/windyGex/preact-test-utils). It only mock [some apis](https://github.com/airbnb/enzyme/blob/master/src/react-compat.js) that used in enzyme, I found enzyme access internal properties of react, but preact-compat have not these properties. So I want to push this code to preact-compat.
Now It can support `mount` mode test using enzyme. Maybe it can support `shallow` mode when your `preact-shallow-render` release.

### CODE REVIEW

**Comment by developit** [comment]
Oh wow, this is quite the major change!  All good stuff, just there's a lot of things here that seem to be duplicated in [preact/devtools](https://github.com/developit/preact/blob/master/devtools/devtools.js).  Maybe @robertknight can help us shine some light on things since he knows a lot about this stuff too.

For my own initial look through the code, I'd like to see if we could use getters instead of `componentDidMount()` to allow tree traversal.  The current implementation would be a fairly huge performance hit because it crawls the DOM after every mount in order to regenerate the mocked React tree.  Also not sure how that would handle updates (since they don't trigger a remount).

**Comment by windyGex** [comment]
Thx for your review. I will use gettters instead of call patch method after `componentdidMount` and `componentDidUpdate`.
Yes. It inspired by `preact/devtools`. Please @robertknight review it.

**Comment by windyGex** [comment]
Any news？ @developit @robertknight

**Comment by developit** [comment]
@windyGex Been sitting on this because of the filesize hit. Still thinking.

**Comment by windyGex** [comment]
Should not quality be more important than file size? Especially in the production environment. We should make a balance between them. We plan to replace react with preact on Alibaba.com to improve rendering performance, but now lacks the safeguard of unit test. Sorry for my poor English.

**Comment by developit** [comment]
@windyGex Absolutely, sorry - I didn't mean to imply that file size was more important.  I just am looking for ways to slim the other parts of `preact-compat` down in order to offset the cost of this.

What would you think of moving your changes under a conditional that is removed in prod?  I think they are mainly used by Enzyme, so that might work here?
Something like this:

```
if (process.env.NODE_ENV!=='production') {
  // ...
}
```

**Comment by windyGex** [comment]
I found code like this:
https://github.com/developit/preact-compat/blob/master/src/index.js#L33
```js
if (DEV) {
 
}
```

Can I use this code directly?

**Comment by developit** [comment]
@windyGex should be able to, yes - if the added properties are primarily used for testing, I think this might work well.

**Comment by windyGex** [comment]
I have moved this code to dev mode. Please review it. Thx.

**Comment by developit** [comment]
Perfect, thanks. Will be looking into this today, hopefully we can merge! :)

**Comment by moimikey** [comment]
🌈

**Comment by developit** [comment]
Thanks for the reminder, haha. Super busy with Preact 8 but I've been pondering this.

**Comment by davesnx** [comment]
Hey, I would love to have this 👍 

Any way that we can help to be merged? Seems pretty traight forward...

**Comment by developit** [comment]
Ends up being a battle of filesizes.  I think we can marge this and test it out though, I believe @windyGex is already using it.

**Comment by armand1m** [comment]
Would be nice to see it merged =)

**Comment by windyGex** [comment]
Now your can use [`preact-compat-enzyme`](https://github.com/windyGex/preact-compat-enzyme) alias for `react`, `react-dom` when writing unit test using enzyme.

**Comment by developit** [comment]
@windyGex that is awesome!

**Pull request closed without merging**
