### PR TITLE
Add (incomplete) TypeScript declaration

### PR DESCRIPTION
**Pull request by jokester**
I wrote this when updating my [CRA + preact + TypeScript](https://github.com/jokester/typescript-boilerplate/tree/master/browser-preact) boilerplate. Same idea as in #357 , plus a few new names added by preact-compat that I needed.

Hope this can be a start of (often tricky) TS support :shamrock: . Any ideas are welcome.

This declaration should allow people to `import React / ReactDOM from 'preact-compat';`, but was created with no webpack-aliasing and tsc-aliasing in mind. I'm particularly open to tests / changes that help to be compatible with them.

### CODE REVIEW

**Comment by jokester** [comment]
A minimum test with CRA: https://github.com/jokester/typescript-boilerplate/commit/3301e1795bff3675104b17c528f0de252dae6cca

**Comment by jokester** [comment]
Hello there. Not sure how PR is done commonly but, can I have some review on this? @developit

**Comment by developit** [comment]
@jokester sorry for the long review time - this seems odd to me, though: most folks just use the React tsd for preact-compat, since the API's are the same. Thoughts?

**Comment by jokester** [comment]
Thanks for the reply. I'm totally ok to close this.

**Pull request closed without merging**
