### PR TITLE
Add createRef

### PR DESCRIPTION
**Pull request by developit**
Implemented in developit/preact#1138, we just have to export it here.
This won't do anything until Preact 8.4.0 is released.

### CODE REVIEW

**Comment by hontas** [comment]
Any updates on when we can expect this in the open?

**Comment by developit** [comment]
@hontas sorry for the delay in replying - this PR is waiting on Preact 8.4.0. The [upstream PR](https://github.com/developit/preact/pull/1138) has been merged, so the release should go out pretty soon. I believe it was stalled on determining if it would be an 8.4 or a 9.0 release since there are other API changes afoot.

**Comment by timnovis** [comment]
Hey! Any ideas when this will go out now that the new release of preact has been published?

**Comment by developit** [comment]
ha! thanks for the tip-off @timnovis, I had forgotten to publish. Time for a preact-compat release I guess!

**Comment by tombuckley91** [comment]
Hey @developit - Can we expect this release imminently? I've made the change locally so I can get some stuff done but I'm just conscious that it won't work for anyone else who pulls my branch down, thanks again dude! 👍

**Pull request merged**
