### PR TITLE
Implement createPortal(). Fixes #452.

### LINKED ISSUE #452: Implement createPortal API
https://reactjs.org/docs/portals.html

### PR DESCRIPTION
**Pull request by developit**
Needs a test or two.

Note: this does not implement [event bubbling redirection](https://reactjs.org/docs/portals.html#event-bubbling-through-portals), since doing so would be rather difficult in Preact.

### CODE REVIEW

**Comment by developit** [comment]
Ooooh you're right. That's a killer Preact hack ;)

**Comment by lukeed** [comment]
tumblr_mezprb2brl1rxa4z0

**Comment by andersontr15** [comment]
Can't see this in `^3.18.0` under `src/index.js`. Am I missing something?

**Comment by lukeed** [comment]
Looks like hasn't been published yet

**Comment by maka-io** [comment]
Any minute?

**Comment by developit** [comment]
It's in [3.18.2](https://github.com/developit/preact-compat/releases/tag/3.18.2).

**Comment by doxiaodong** [comment]
https://github.com/ant-design/ant-design-mobile/pull/2764

**Pull request merged**
