### PR TITLE
Make process shim not necessary on production environments

### LINKED ISSUE #403: Remove `process/browser.js`
In continuation of #285, I found that `preact-compat` was forcing Webpack to include a `process` shim.

I was able to remove it locally by changing:

```js
var DEV = typeof process==='undefined' || !process.env || process.env.NODE_ENV!=='production';
```

to this:

```js
var DEV = process.env.NODE_ENV!=='production';
```

I can open a PR for this if you don't see a problem with it? Everyone & their mother uses some kind of bundler now, and all bundlers have a `replaceText` or `DefinePlugin` capability. 

For example, with webpack, I did this, the oldest trick in the book:

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(isProd ? 'production' : 'development')
}),
```

Before:

screen shot 2017-07-13 at 6 49 59 pm

After: 

screen shot 2017-07-13 at 6 53 34 pm

---

Worth noting that the `DefinePlugin` trick does not work unless this change is made. This is because instances of `'process'` are found, thus loading the polyfill.

### PR DESCRIPTION
**Pull request by kaisermann**
Fixes #403

### CODE REVIEW

**Comment by kaisermann** [comment]
I agree, done!

**Comment by k1r0s** [comment]
@lukeed I would preffer @kaisermann statement since is more easy to read and has no chance to raise NPE

**Comment by k1r0s** [comment]
LGFM! any comments before merging?

**Comment by lukeed** [comment]
Nope~! I don't think mine is any harder to read, but I'm happy as long as a solution works 😄

**Comment by k1r0s** [comment]
Slightly hard haha, both are easy to read sorry :)

**Pull request merged**
