### PR TITLE
Use reactjs offical proptypes lib.

### PR DESCRIPTION
**Pull request by tkh44**

### CODE REVIEW

**Comment by developit** [comment]
Oooh, it's 1kb instead of 1.6kb too!

**Comment by developit** [comment]
Hmm - looks like its a noop in prod but fairly large in dev.

I'm getting an error though when I try to emulate this on jsfiddle: it seems like the new prop-types module doesn't allow manual validation?  They require that you have access to an internal object for some reason:
https://jsfiddle.net/developit/agc04zgv/

**Comment by tkh44** [comment]
@developit have you tried in combination with #350? I've been running this combo locally with success.

**Comment by developit** [comment]
@tkh44 Are we good to merge #359 instead of this since it fixes the `checkPropTypes` strictness issue?

**Comment by tkh44** [comment]
Yes @developit. Ill go ahead and close this PR.

**Pull request closed without merging**
