### PR TITLE
Amends "Object.defineProperty" instances, making them "configurable".

### PR DESCRIPTION
**Pull request by ctrlplusb**
This resolves issues with using hot reloading techniques provided by tools such as Webpack.

Originally reported in https://github.com/developit/preact/issues/168

### CODE REVIEW

**Comment by ctrlplusb** [comment]
As they are getter/setter properties I couldn't make them writable, as per spec.

I tested this against a personal project and the HMR was successful, however, it was appending to the container HTML element rather than replacing the existing content.

I had to first clear my container like so:

```javascript
while (container.firstChild) {
  container.removeChild(container.firstChild);
}
```

Before rendering like so

```javascript
import { render } from 'react-dom/server';

render(<Foo />, container);
```

Is this a bug with the current `render` implementation?

**Comment by developit** [comment]
@ctrlplusb I haven't seen this technique used for server rendering. For `react-dom`'s render (the client side one), preact normally appends instead of replacing, and accepts a third argument that is the element to replace. `preact-compat` patches this, maybe there is a bug?

**Comment by ctrlplusb** [comment]
Woops!  Typo in my example, was import from `react-dom` not `react-dom/server`.

Hmmm, it's defo doing the default `preact`-like behaviour then.  I'll ping a look see.

**Comment by ctrlplusb** [comment]
Ok, I did some initial research.  I _think_ the issue may lie with `preact` and not `preact-compat`.

I tried the following code to test that the API worked as you described above:

```javascript
import { h, render } from 'preact';
const foo = (<div>foo</div>);
const bar = (<div>bar</div>);
render(foo, document.querySelector('#app'));
render(bar, container, foo);
```

I am completely new to `preact` though, so hopefully I have understood you correctly. Should the above code snippet result in an output of `<div>bar</div>` on screen, replacing `<div>foo</div>`?

This failed. :(

screenshot 2016-07-18 23 11 18

**Comment by developit** [comment]
@ctrlplusb Ah - I should have explained better: `render()` actually returns the root node, which you can pass as the third argument on a subsequent render to update in-place:

```js
import { h, render } from 'preact';
const foo = (<div>foo</div>);
const bar = (<div>bar</div>);
const container = document.querySelector('#app');

let root = render(foo, container);
root = render(bar, container, root);
```

With preact-compat, this is patched for you, so the following should work:

```js
import { createElement, render } from 'preact-compat';
const foo = (<div>foo</div>);
const bar = (<div>bar</div>);
const container = document.querySelector('#app');

render(foo, container);
render(bar, container);
```

It's possible that there is an issue when your root element is not a Component, though.

**Pull request merged**
