### PR TITLE
Merge mixin return values

### LINKED ISSUE #239: getInitialState doesn't merge return values
It is possible to have `getInitialState` implemented with `React.createClass`, and also have one (or more) mixins implement `getInitialState` as well.

React will merge the objects returned from all these functions, throwing an error if there are any duplicate keys.

Thanks for the cool project :)

### PR DESCRIPTION
**Pull request by Stuk**
Fixes #239.

Let me know if anything isn't clear or is just plain wrong. Happy to make changes :)

### CODE REVIEW

**Comment by Stuk** [comment]
I've rebased on top of master, and improved the changes

**Comment by Aweary** [comment]
@developit is this still under review? We use a lot of this state composition with mixins in Electrode, would love to see this merged and would be happy to help review.

**Comment by developit** [comment]
Top of my list. Does it look good to you? I don't use mixins so I'm just basing it off the public React API.

**Comment by Aweary** [comment]
@developit it looks solid to me, and if the tests pass I think it's probably good to go.

**Comment by developit** [comment]
Alrighty! It bumps the file size up a little bit, but I'm hoping to deal with that shortly.

**Pull request merged**
